version: '3.8' 
services:
  #csvserver
  csv:
   image: "infracloudio/csvserver"
   ports:
     - "9393:9300"
   volumes:
   - "./inputdata:/csvserver/inputdata"
   env_file: 
   - csvserver.env 
  #prometheus
  prometheus:
   image: "prom/prometheus:v2.45.2"
   ports:
     - "9090:9090"
   volumes:
     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    
